# Generated by Django 6.0.4 on 2026-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo Academico')),
                ('biografia', models.CharField(max_length=100, verbose_name='Biografia')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('trabajo', models.CharField(max_length=100, verbose_name='Ocupacion')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='fecha de Creacion')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'db_table': 'Persona',
                'ordering': ['-create'],
            },
        ),
    ]
